### ISSUE TITLE
Arbitrary getting stuck

### ISSUE THREAD

**Issue by yairchu** [typeable/generic-arbitrary#5]
I tried the following:

```Haskell
data Expr
    = Lit Int
    | Add Expr Expr
    | Mul Expr Expr
    deriving (Eq, Show, Generic)

instance Arbitrary Expr where
    arbitrary = genericArbitrary
    shrink = genericShrink

> generate arbitrary :: IO Expr
```

This usually never finishes, generating an infinitely large expression.

It did take a while to figure out that the arbitrary instance generates an infinite value rather than my other code getting stuck in an infinite loop.

I then tried using [`quickcheck-arbitrary-adt`](http://hackage.haskell.org/package/quickcheck-arbitrary-adt) instead and my problem was solved. I'm not sure what the differences between the packages are.

Cheers! Yair

**Comment by cdornan** [comment]
I have observed this behaviour also.

**Comment by int-index** [comment]
The code in this package is fairly simplistic and does not account for recursive data types, handling of which requires managing a size parameter to avoid infinitely large data structures.

**Comment by ilyakooo0** [comment]
@s9gf4ult was this fixed in #16?

**Comment by s9gf4ult** [comment]
It must be

**Comment by s9gf4ult** [comment]
@yairchu could you check the issue is fixed?

**Comment by yairchu** [comment]
Yes it appears to work now!

Note that the behavior just before #16 doesn't appear to be the original reported error (getting stuck) but rather an exception

```
ghci> generate arbitrary :: IO Expr
Add (Lit 8) (Mul (Lit 24) (Add (Add (Add (Mul (Mul (Mul (Add (Add (Mul (Lit 7) (Lit 2)) (Mul (Add (Add (Lit (-1)) (Mul (Lit (-1)) (Mul (Lit *** Exception: Test.QuickCheck.resize: negative size
CallStack (from HasCallStack):
  error, called at src/Test/QuickCheck/Gen.hs:135:22 in QuickCheck-2.14.2-IPNJa1QnCJsJHr6jmhnfPF:Test.QuickCheck.Gen
```
